cp index.html.template index.html
cat index.html
(
echo '/<!-- AUTOGENERATED PLEASE DO NOT EDIT: BEGIN -->/'; echo a;
find . -mindepth 2 -name index.html | sed 's/\.\///g' | sed 's/\/index\.html//g' | sed 's/\// /' | sort | awk '
    {
	start_block = 0
        end_block = 0
    }
    BEGIN { 
        prev = ""
	start_block = 1
    }
    NR == 1 {
        start_block = 1
    }
    NR > 1 && $1 != prev {
        end_block = 1
        start_block = 1
    }
    { prev = $1 }
    END { printf("        </ul>\n    </nav>\n</div>\n") }
    end_block == 1 { printf("        </ul>\n    </nav>\n</div>\n") }
    start_block == 1 { printf("<div class=\"project-tile\">\n    <nav role=\"navigation\">\n        <ul class=\"summary\">\n            <h1 class=\"project-header\">%s</h1>\n", $1) }
    { printf("\n            <li class=\"chapter active\" data-level=\"1.1\" data-path=\"./\">\n                <a href=\"%s/%s\">%s</a>\n            </li>\n", $1, $2, $2) }
'; echo .; echo wq
) | ed index.html
